# Generated by Django 4.1.7 on 2023-02-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_score_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='score',
            new_name='answer_score',
        ),
        migrations.AddField(
            model_name='profile',
            name='question_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
