# Generated by Django 4.1.7 on 2023-02-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_score_profile_answer_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answer_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='question_score',
        ),
    ]
