# Generated by Django 4.1.7 on 2023-02-26 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_answer_is_rated_down_answer_is_rated_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_score',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_rated_down',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_rated_up',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_rated_down',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_rated_up',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_score',
        ),
        migrations.CreateModel(
            name='QuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rated_up', models.BooleanField(default=False)),
                ('is_rated_down', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rated_up', models.BooleanField(default=False)),
                ('is_rated_down', models.BooleanField(default=False)),
                ('question_score', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
